[pytest]
filterwarnings =
    error
    ignore::UserWarning
    ignore::DeprecationWarning:testcontainers
    ignore::DeprecationWarning:datajoint
    ignore::pydantic.warnings.PydanticDeprecatedSince211
    ignore::DeprecationWarning:pkg_resources

addopts=-s