# PHARUS_VERSION=0.1.0 DJLABBOOK_VERSION=0.1.0 docker-compose -f docker-compose-deploy.yaml pull
# PHARUS_VERSION=0.1.0 DJLABBOOK_VERSION=0.1.0 docker-compose -f docker-compose-deploy.yaml up -d
#
# Intended for production deployment.
# Note: You must run both commands above for minimal outage.
# If you don't update your hosts file, you will still have access at `https://localhost`
# however it should simply display 'Not secure' since the cert will be invalid.
version: "2.4"
x-net: &net
  networks:
      - main
services:
  pharus:
    <<: *net
    image: datajoint/pharus:${PHARUS_VERSION}
    environment:
      - PHARUS_PORT=5000
  labbook:
    <<: *net
    image: drewyangdev/datajoint-labbook:v0.1.1
    depends_on:
      pharus:
        condition: service_healthy
  reverse-proxy:
    image: datajoint/nginx:v0.1.0
    environment:
      - ADD_pharus_TYPE=REST
      - ADD_pharus_ENDPOINT=pharus:5000
      - ADD_pharus_PREFIX=/utils
      - ADD_sciviz_TYPE=REST
      - ADD_sciviz_ENDPOINT=labbook:80
      - ADD_sciviz_PREFIX=/
      - DEPLOYMENT_PORT
    ports:
      #      - "443:443"
      - "${DEPLOYMENT_PORT}:80"
    <<: *net
networks:
  main:
