#! /bin/bash

#> cd docker/.devcontainer
#> chmod +x vscode-open-dev-container
#> ./vsc*

relative_ws="../.."
ws_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/${relative_ws}" &>/dev/null && pwd)"

if ! command -v devcontainer &>/dev/null; then
	echo "#! Error: 'devcontainer' CLI not found. https://code.visualstudio.com/docs/remote/devcontainer-cli"
	exit 1
fi

devcontainer open "${ws_root}/docker"
