#! /bin/bash

#> cd docker/.devcontainer
#> chmod +x vscode-open-dev-container
#> ./vsc*

ws_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." &>/dev/null && pwd)"

if ! command -v devcontainer &>/dev/null; then
	echo "#! Error: 'devcontainer' CLI not found. https://code.visualstudio.com/docs/remote/devcontainer-cli"
	exit 1
fi

[[ -f "${ws_root}/docker/.env" ]] && touch "${ws_root}/docker/.env"
[[ -f "${ws_root}/docker/dev.env" ]] && touch "${ws_root}/docker/dev.env"

devcontainer open "${ws_root}/docker"
