"""DataJoint schema to process mouse movement / position data.

Downstream of ``streams.CameraPosition`` and ``streams.CameraVideo``. Because
those stream tables are auto-generated by ``streams_maker`` only when an
experiment registers a camera device that produces position+video streams,
this module uses **deferred schema activation**: tables are defined against
an unbound ``dj.Schema()`` at import time, and ``activate()`` only binds them
to the database if the required upstream stream tables exist.

The canonical caller is ``aeon.dj_pipeline.__init__``, which invokes
``activate()`` after ``streams_maker`` has run. If the upstream streams are
not present, activation is a logged no-op and ``MousePositionTracking``
simply remains undeclared.

If new camera experiments are registered later in the same Python session,
re-running ``activate()`` picks them up.
"""

import datajoint as dj
import numpy as np
import pandas as pd

from aeon.dj_pipeline import get_schema_name, streams

schema = dj.Schema()
logger = dj.logger


@schema
class MousePositionTracking(dj.Computed):
    definition = """
    -> streams.CameraPosition
    ---
    nr_nans: int32            # Number of timestamps with no detected position
    timestamps: <blob>        # datetime timestamps
    x: <blob>                 # X position (pixels)
    y: <blob>                 # Y position (pixels), y axis top to bottom
    area: <blob>              # Area of the blob (pixels^2)
    """

    def make(self, key):
        """Merge objects from different object_ids."""
        position_df = (streams.CameraPosition() & key).fetch1("stream_df")
        position_df = position_df.reset_index()

        # sometimes multiple blobs are detected (e.g. mouse outline split into multiple blobs)
        # this results in duplicated timestamps with different id
        duplicated_mask = position_df["time"].duplicated(keep=False)

        # get all duplicated timestamps, where mouse was detected as multiple blobs
        dfs_dup = position_df[duplicated_mask]
        timestamps = dfs_dup["time"].unique()

        curated_locations = []

        for t in timestamps:
            df_t = dfs_dup[dfs_dup["time"] == t]

            # calculate x,y as weighted average by area
            total_area = df_t["area"].sum()
            x = np.sum(df_t["x"] * df_t["area"]) / total_area
            y = np.sum(df_t["y"] * df_t["area"]) / total_area
            curated_locations.append({"time": t, "x": x, "y": y, "area": total_area})

        # merge curated locations with unique entries in the table
        df_curated = pd.DataFrame(curated_locations)
        df_unique = position_df[~position_df["time"].isin(timestamps)]
        df_unique = df_unique[["time", "x", "y", "area"]]
        df_curated = pd.concat([df_unique, df_curated], ignore_index=True)
        df_curated.sort_values("time", inplace=True)
        df_curated.reset_index(drop=True, inplace=True)

        # Add nan values for timestamps that are missing in the original data
        video_timestamps = (streams.CameraVideo() & key).fetch1("stream_df").index

        # get timestamps missing in df_curated
        missing_timestamps = video_timestamps.difference(pd.DatetimeIndex(df_curated["time"]))

        # create dataframe with missing timestamps and -1000 (as nan) values.
        # negative values used to avoid concatenation issues with all np.nan columns
        df_missing = pd.DataFrame({"time": missing_timestamps, "x": -1000, "y": -1000, "area": -1000})

        # merge and sort in time
        df_curated = pd.concat([df_curated, df_missing], ignore_index=True)
        df_curated.sort_values("time", inplace=True)
        df_curated.reset_index(drop=True, inplace=True)

        # change -1000 values to np.nan
        df_curated.loc[df_curated["x"] == -1000, "x"] = np.nan
        df_curated.loc[df_curated["y"] == -1000, "y"] = np.nan
        df_curated.loc[df_curated["area"] == -1000, "area"] = np.nan

        # Add entry to database
        new_entry = {
            **key,
            "nr_nans": int(df_curated["x"].isna().sum()),
            "timestamps": df_curated["time"].values,
            "x": df_curated["x"].values,
            "y": df_curated["y"].values,
            "area": df_curated["area"].values,
        }
        self.insert1(new_entry)


@schema
class VideoQC(dj.Computed):
    definition = """
    -> streams.CameraVideo
    ---
    violation_count: int32    # number of temporal violations detected
    violation_times: <blob>   # (datetime) timestamps
    duplicate_count: int32    # number of duplicate timestamps detected
    duplicate_times: <blob>   # (datetime) timestamps
    """

    def make(self, key):
        """Detect duplication and violation of temporal order of video data."""
        video_df = (streams.CameraVideo & key).fetch1("stream_df")
        t = video_df.index.values

        # Get violations
        # Could get from duplicate detection, but this provides more clarity
        violation_frames = t.argsort() - np.arange(len(t))
        violation_mask = violation_frames < 0
        violation_count = int(np.sum(violation_mask))
        violation_times = t[violation_mask]

        # Get duplicates
        duplicate_mask = np.diff(t) == np.timedelta64(0)
        duplicate_count = int(np.sum(duplicate_mask))
        duplicate_times = t[np.where(duplicate_mask)[0] + 1]

        new_entry = {
            **key,
            "violation_count": violation_count,
            "violation_times": violation_times,
            "duplicate_count": duplicate_count,
            "duplicate_times": duplicate_times,
        }
        self.insert1(new_entry)


_REQUIRED_STREAMS = ("CameraPosition", "CameraVideo")


def activate(*, create_schema: bool = True, create_tables: bool = True) -> bool:
    """Bind the processed_movement schema to the database if upstream streams exist.

    Checks that ``streams.CameraPosition`` and ``streams.CameraVideo`` are both
    present as Python attributes — i.e. that ``streams_maker`` has already
    generated them from a registered camera device. If any are missing, logs a
    warning and returns ``False`` without touching the database.

    Re-callable: if new camera experiments are registered later in the same
    Python session and ``streams_maker`` regenerates the missing tables,
    invoking this again will activate the schema.

    Returns:
        True if the schema was activated, False if upstream streams missing.
    """
    if streams is None:
        logger.warning("processed_movement not activated — streams module not initialized")
        return False
    missing = [t for t in _REQUIRED_STREAMS if not hasattr(streams, t)]
    if missing:
        logger.warning(f"processed_movement not activated — streams missing: {missing}")
        return False
    schema.activate(
        get_schema_name("processed_movement"),
        create_schema=create_schema,
        create_tables=create_tables,
    )
    return True
