#----                     DO NOT MODIFY                ----
#---- THIS FILE IS AUTO-GENERATED BY `streams_maker.py` ----

import re
import datajoint as dj
import pandas as pd
from uuid import UUID

import aeon
from aeon.dj_pipeline import acquisition, get_schema_name
from swc.aeon.io import api as io_api

schema = dj.Schema(get_schema_name("streams"))


@schema
class StreamType(dj.Lookup):
    """Catalog of unique stream types used across Project Aeon.

    Each entry represents a unique combination of stream_type name and reader class.
    The stream reader is resolved at runtime via the Pydantic Device class hierarchy,
    using @data_reader decorated methods. The stream_hash uniquely identifies each
    (stream_type, stream_reader) combination to handle cases where different experiments
    define the same stream_type name with different underlying readers.
    """

    definition = """ # Catalog of unique stream types used across Project Aeon
    stream_hash: uuid  # hash(stream_type, stream_reader) - unique identifier
    ---
    stream_type: varchar(36)  # stream type name, e.g., "Video", "BeamBreak"
    stream_reader: varchar(256)  # reader class path for documentation, e.g., "swc.aeon.io.reader.Video"
    stream_reader_kwargs=null: <blob>  # JSON dict of reader constructor kwargs (value, tag, columns, etc.)
    stream_description='': varchar(256)
    unique index(stream_type, stream_reader)
    """


@schema
class DeviceType(dj.Lookup):
    """Catalog of all device types used across Project Aeon."""

    definition = """  # Catalog of all device types used across Project Aeon
    device_type:             varchar(36)
    ---
    device_description='':   varchar(256)
    """

    class Stream(dj.Part):
        """Links device types to their associated stream types.

        Each entry specifies which StreamType (identified by stream_hash) is
        associated with a given device type. This allows the same device type
        to have multiple streams, and handles cases where different experiments
        use the same stream_type name with different reader implementations.
        """

        definition = """  # Data stream(s) associated with a particular device type
        -> master
        -> StreamType
        """


@schema
class DeviceName(dj.Lookup):
    definition = """  # Catalog of device instance names
    device_name: varchar(36)
    ---
    -> DeviceType
    """


