# Create env e.g. w/mamba: `mamba env create -q -f conda_env.yml`
# Update existing env e.g. w/mamba: `mamba env update -f conda_env.yml`

name: aeon
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.13
