#! /bin/bash

_USER_NAME="${USER_NAME}"
_USER_GROUP="${USER_GROUP:-$(id -gn)}"

if [[ -z "${_USER_NAME}" ]]; then
	echo "# ~Warning: user USER_NAME=$_USER_NAME not found!"
	echo "running 'conda-run $*' as current user w/o sudo: '$(id)'"
	exec conda-run "$@"
fi

# sudo -EHn -u USERNAME -g GROUPNAME bash -l
exec sudo --preserve-env --set-home --non-interactive -u $_USER_NAME -g $_USER_GROUP \
	bash -s "$@" <<-'EOF'
		conda-run "$@"
	EOF
